# Generated by Django 4.2.3 on 2023-08-19 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worshipKart', '0002_delete_productsubcategory_remove_productcategory_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='productCategory',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='worshipKart.productcategory'),
        ),
    ]
