# Generated by Django 4.2.3 on 2023-08-22 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worshipKart', '0003_products_productcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='categoryImages',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
