# Generated by Django 4.2.3 on 2023-08-22 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worshipKart', '0004_productcategory_categoryimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='categoryImages',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
