# Generated by Django 4.2.3 on 2023-08-30 12:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worshipKart', '0006_orderproduct_quantity_orders_orderproduct_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='complaints',
            fields=[
                ('complaintID', models.AutoField(primary_key=True, serialize=False)),
                ('complaintDate', models.DateField(default=datetime.date.today)),
                ('complaintType', models.CharField(choices=[('Product Related', 'Product Related'), ('Delivery related', 'Delivery related'), ('Payment Related', 'Payment Related'), ('Others', 'Others')], default='Others', max_length=100)),
                ('complaintStatus', models.CharField(choices=[('Open', 'Open'), ('Awaiting Customer Response', 'Awaiting Customer Response'), ('Under Review', 'Under Review'), ('Resolved', 'Resolved'), ('Awaiting Vendor Response', 'Awaiting Vendor Response')], default='Open', max_length=100)),
                ('issue', models.TextField()),
                ('response', models.TextField(blank=True, null=True)),
                ('responseDate', models.DateField(blank=True, null=True)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worshipKart.usermaster')),
            ],
        ),
    ]
